// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAOuHvHjlfzMTBREVaWac_mc1eMiS3yVE',
    appId: '1:54395680658:web:51a19a78c5a6ff42b5734b',
    messagingSenderId: '54395680658',
    projectId: 'design-grid-ai',
    authDomain: 'design-grid-ai.firebaseapp.com',
    storageBucket: 'design-grid-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrFtIj6-g7G6-IqHxuNb9ZIde_7EQE4wg',
    appId: '1:54395680658:android:a4b3fe83083b7655b5734b',
    messagingSenderId: '54395680658',
    projectId: 'design-grid-ai',
    storageBucket: 'design-grid-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2xwZYE0S9V6cEYA3_a2fsexjZH_NN0c',
    appId: '1:54395680658:ios:7442875ea963ef19b5734b',
    messagingSenderId: '54395680658',
    projectId: 'design-grid-ai',
    storageBucket: 'design-grid-ai.firebasestorage.app',
    iosBundleId: 'com.designgrid.designgridAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy2xwZYE0S9V6cEYA3_a2fsexjZH_NN0c',
    appId: '1:54395680658:ios:7442875ea963ef19b5734b',
    messagingSenderId: '54395680658',
    projectId: 'design-grid-ai',
    storageBucket: 'design-grid-ai.firebasestorage.app',
    iosBundleId: 'com.designgrid.designgridAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAOuHvHjlfzMTBREVaWac_mc1eMiS3yVE',
    appId: '1:54395680658:web:407fe0ce5cd5d307b5734b',
    messagingSenderId: '54395680658',
    projectId: 'design-grid-ai',
    authDomain: 'design-grid-ai.firebaseapp.com',
    storageBucket: 'design-grid-ai.firebasestorage.app',
  );
}
